/**
 * Swagger XGasto API
 * Documentação da API de acesso aos endpoints com Swagger
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs/Observable';

import { GastoDto } from '../model/gastoDto';
import { ResponseGastoDto } from '../model/responseGastoDto';
import { Responsestring } from '../model/responsestring';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class GastoControllerService {

    protected basePath = 'http://localhost:8080';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * create
     * 
     * @param idConta IdConta
     * @param idCategoria IdCategoria
     * @param gastoDto gastoDto
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public createUsingPOST1(idConta: number, idCategoria: number, gastoDto: GastoDto, observe?: 'body', reportProgress?: boolean): Observable<ResponseGastoDto>;
    public createUsingPOST1(idConta: number, idCategoria: number, gastoDto: GastoDto, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ResponseGastoDto>>;
    public createUsingPOST1(idConta: number, idCategoria: number, gastoDto: GastoDto, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ResponseGastoDto>>;
    public createUsingPOST1(idConta: number, idCategoria: number, gastoDto: GastoDto, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idConta === null || idConta === undefined) {
            throw new Error('Required parameter idConta was null or undefined when calling createUsingPOST1.');
        }

        if (idCategoria === null || idCategoria === undefined) {
            throw new Error('Required parameter idCategoria was null or undefined when calling createUsingPOST1.');
        }

        if (gastoDto === null || gastoDto === undefined) {
            throw new Error('Required parameter gastoDto was null or undefined when calling createUsingPOST1.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (idConta !== undefined && idConta !== null) {
            queryParameters = queryParameters.set('IdConta', <any>idConta);
        }
        if (idCategoria !== undefined && idCategoria !== null) {
            queryParameters = queryParameters.set('IdCategoria', <any>idCategoria);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<ResponseGastoDto>(`${this.basePath}/api/gasto/create`,
            gastoDto,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * delete
     * 
     * @param idGasto idGasto
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteUsingDELETE1(idGasto: number, observe?: 'body', reportProgress?: boolean): Observable<Responsestring>;
    public deleteUsingDELETE1(idGasto: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Responsestring>>;
    public deleteUsingDELETE1(idGasto: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Responsestring>>;
    public deleteUsingDELETE1(idGasto: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idGasto === null || idGasto === undefined) {
            throw new Error('Required parameter idGasto was null or undefined when calling deleteUsingDELETE1.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.delete<Responsestring>(`${this.basePath}/api/gasto/delete/${encodeURIComponent(String(idGasto))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * update
     * 
     * @param idGasto idGasto
     * @param idCategoria idCategoria
     * @param gastoDto gastoDto
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updateUsingPUT1(idGasto: number, idCategoria: number, gastoDto: GastoDto, observe?: 'body', reportProgress?: boolean): Observable<ResponseGastoDto>;
    public updateUsingPUT1(idGasto: number, idCategoria: number, gastoDto: GastoDto, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ResponseGastoDto>>;
    public updateUsingPUT1(idGasto: number, idCategoria: number, gastoDto: GastoDto, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ResponseGastoDto>>;
    public updateUsingPUT1(idGasto: number, idCategoria: number, gastoDto: GastoDto, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idGasto === null || idGasto === undefined) {
            throw new Error('Required parameter idGasto was null or undefined when calling updateUsingPUT1.');
        }

        if (idCategoria === null || idCategoria === undefined) {
            throw new Error('Required parameter idCategoria was null or undefined when calling updateUsingPUT1.');
        }

        if (gastoDto === null || gastoDto === undefined) {
            throw new Error('Required parameter gastoDto was null or undefined when calling updateUsingPUT1.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (idGasto !== undefined && idGasto !== null) {
            queryParameters = queryParameters.set('idGasto', <any>idGasto);
        }
        if (idCategoria !== undefined && idCategoria !== null) {
            queryParameters = queryParameters.set('idCategoria', <any>idCategoria);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.put<ResponseGastoDto>(`${this.basePath}/api/gasto/update`,
            gastoDto,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
