/**
 * Swagger XGasto API
 * Documentação da API de acesso aos endpoints com Swagger
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs/Observable';

import { ResponsePessoaDto } from '../model/responsePessoaDto';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class PessoaControllerService {

    protected basePath = 'http://localhost:8080';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * findById
     * 
     * @param id id
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public findByIdUsingGET(id: number, observe?: 'body', reportProgress?: boolean): Observable<ResponsePessoaDto>;
    public findByIdUsingGET(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ResponsePessoaDto>>;
    public findByIdUsingGET(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ResponsePessoaDto>>;
    public findByIdUsingGET(id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling findByIdUsingGET.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<ResponsePessoaDto>(`${this.basePath}/api/pessoa/findById/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * registerUser
     * 
     * @param nome nome
     * @param email email
     * @param password password
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public registerUserUsingPOST(nome: string, email: string, password: string, observe?: 'body', reportProgress?: boolean): Observable<ResponsePessoaDto>;
    public registerUserUsingPOST(nome: string, email: string, password: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ResponsePessoaDto>>;
    public registerUserUsingPOST(nome: string, email: string, password: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ResponsePessoaDto>>;
    public registerUserUsingPOST(nome: string, email: string, password: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (nome === null || nome === undefined) {
            throw new Error('Required parameter nome was null or undefined when calling registerUserUsingPOST.');
        }

        if (email === null || email === undefined) {
            throw new Error('Required parameter email was null or undefined when calling registerUserUsingPOST.');
        }

        if (password === null || password === undefined) {
            throw new Error('Required parameter password was null or undefined when calling registerUserUsingPOST.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (nome !== undefined && nome !== null) {
            queryParameters = queryParameters.set('nome', <any>nome);
        }
        if (email !== undefined && email !== null) {
            queryParameters = queryParameters.set('email', <any>email);
        }
        if (password !== undefined && password !== null) {
            queryParameters = queryParameters.set('password', <any>password);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.post<ResponsePessoaDto>(`${this.basePath}/api/pessoa`,
            null,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
